version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    user: 996:100
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - POSTGRES_PASSWORD=${DBPASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    user: 996:100
    restart: always
    ports:
      - 28080:8080
    networks:
      - db-network
      - default
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: 995:100
    ports:
     - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - TZ=America/Los_Angeles
    networks:
      - db-network
      - default

# Note: may need to run docker compse build before docker compose up
  python-server:
    container_name: python-server
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 38080:8080
    depends_on:
      - db
    environment:
      - TZ=America/Los_Angeles
  
networks:
  default:
    name: docker-sql-server_default 
    driver: bridge
  db-network:
    name: db-network
    driver: bridge
